# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'STUDENT'), (2, 'FACULTY'), (3, 'ANONYMUS')], default=3)),
                ('user_id', models.IntegerField()),
                ('answer_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('qn', models.IntegerField()),
                ('que', models.TextField(max_length=200)),
            ],
        ),
    ]
