# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_form_question_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback_Form',
            new_name='Feedback',
        ),
    ]
