# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170817_0819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_List',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_total_raters',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_total_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_total_raters',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_total_rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='tushar', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'STUDENT'), (2, 'FACULTY')], default=3),
        ),
    ]
